# Predict an individual's creditworthiness using past financial data.

## 1) Importing necessary libraries

In [186]:
import pandas as pd

In [187]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [188]:
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report

## 2) Data exploration

In [189]:
df = pd.read_csv("Credit Score Classification Dataset.csv")
df.head()

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,Female,50000,Bachelor's Degree,Single,0,Rented,High
1,30,Male,100000,Master's Degree,Married,2,Owned,High
2,35,Female,75000,Doctorate,Married,1,Owned,High
3,40,Male,125000,High School Diploma,Single,0,Owned,High
4,45,Female,100000,Bachelor's Degree,Married,3,Owned,High

In [190]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 164 non-null    int64
 1   Gender              164 non-null    str
 2   Income              164 non-null    int64
 3   Education           164 non-null    str
 4   Marital Status      164 non-null    str
 5   Number of Children  164 non-null    int64
 6   Home Ownership      164 non-null    str
 7   Credit Score        164 non-null    str
dtypes: int64(3), str(5)
memory usage: 10.4 KB

In [191]:
df.columns

Index(['Age', 'Gender', 'Income', 'Education', 'Marital Status',
       'Number of Children', 'Home Ownership', 'Credit Score'],
      dtype='str')

## 3) Let's encode our string columns

In [192]:
df['Gender'].value_counts()

gender_order = ['Female', 'Male']

In [193]:
df['Education'].value_counts()

education_order = ['High School Diploma', "Associate's Degree", "Bachelor's Degree", "Master's Degree", "Doctorate"]

In [194]:
df['Marital Status'].value_counts()

marital_status_order = ['Single', 'Married']

In [195]:
df['Home Ownership'].value_counts()

home_ownership_order = ['Rented', 'Owned']

In [196]:
df['Credit Score'].value_counts()

credit_score_order = ['Low', 'Average', 'High']

In [197]:
# Encode categorical columns using OneHotEncoder
categorical_list = [gender_order, education_order, marital_status_order, home_ownership_order, credit_score_order]
encoder = OrdinalEncoder(categories=categorical_list)

# Initialize the OrdinalEncoder with the specified categories
encoder = OrdinalEncoder(categories=categorical_list)

# Select the columns to be encoded
columns_to_encode = ['Gender', 'Education', 'Marital Status', 'Home Ownership', 'Credit Score']

# Fit and transform the selected columns
df[columns_to_encode] = encoder.fit_transform(df[columns_to_encode])

df.head()

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,0.0,50000,2.0,0.0,0,0.0,2.0
1,30,1.0,100000,3.0,1.0,2,1.0,2.0
2,35,0.0,75000,4.0,1.0,1,1.0,2.0
3,40,1.0,125000,0.0,0.0,0,1.0,2.0
4,45,0.0,100000,2.0,1.0,3,1.0,2.0

## 4) SPlitting the dataset

In [198]:
X = df.drop('Credit Score', axis=1)
y = df['Credit Score']

In [199]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## 5) Candidate models

In [ ]:
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)
y_pred_logreg = logreg.predict(X_test)

dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)     
y_pred_dtree = dtree.predict(X_test)

rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

c:\Users\bella\anaconda3\envs\pytorch_env\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## 6) Testing candidate models

In [201]:
logreg_acc = logreg.score(X_test, y_test)
logreg_precision = precision_score(y_test, y_pred_logreg, average='weighted')
logreg_recall = recall_score(y_test, y_pred_logreg, average='weighted')
logreg_f1 = f1_score(y_test, y_pred_logreg, average='weighted')

dtree_acc = dtree.score(X_test, y_test)
dtree_precision = precision_score(y_test, y_pred_dtree, average='weighted')
dtree_recall = recall_score(y_test, y_pred_dtree, average='weighted')
dtree_f1 = f1_score(y_test, y_pred_dtree, average='weighted')

rf_acc = rf.score(X_test, y_test)
rf_precision = precision_score(y_test, y_pred_rf, average='weighted')
rf_recall = recall_score(y_test, y_pred_rf, average='weighted')
rf_f1 = f1_score(y_test, y_pred_rf, average='weighted')

print(f"Logistic Regression - Precision: {logreg_precision:.4f}, Recall: {logreg_recall:.4f}, F1-Score: {logreg_f1:.4f}, Accuracy: {logreg_acc}")
print(f"Decision Tree - Precision: {dtree_precision:.4f}, Recall: {dtree_recall:.4f}, F1-Score: {dtree_f1:.4f}, Accuracy: {dtree_acc}")
print(f"Random Forest - Precision: {rf_precision:.4f}, Recall: {rf_recall:.4f}, F1-Score: {rf_f1:.4f}, Accuracy: {rf_acc}")

Logistic Regression - Precision: 0.9394, Recall: 0.9394, F1-Score: 0.9394, Accuracy: 0.9393939393939394
Decision Tree - Precision: 0.9747, Recall: 0.9697, F1-Score: 0.9707, Accuracy: 0.9696969696969697
Random Forest - Precision: 0.9394, Recall: 0.9394, F1-Score: 0.9394, Accuracy: 0.9393939393939394

The best model seems to be Decision tree

### Classification reports

In [202]:
print("Classification Report for Logistic Regression:")
print(classification_report(y_test, y_pred_logreg))

Classification Report for Logistic Regression:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         5
         1.0       0.80      0.80      0.80         5
         2.0       0.96      0.96      0.96        23

    accuracy                           0.94        33
   macro avg       0.92      0.92      0.92        33
weighted avg       0.94      0.94      0.94        33

In [203]:
print("Classification Report for Decision Tree:")
print(classification_report(y_test, y_pred_dtree))

Classification Report for Decision Tree:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         5
         1.0       0.83      1.00      0.91         5
         2.0       1.00      0.96      0.98        23

    accuracy                           0.97        33
   macro avg       0.94      0.99      0.96        33
weighted avg       0.97      0.97      0.97        33

In [204]:
print("Classification Report for Random Forest:")
print(classification_report(y_test, y_pred_rf))

Classification Report for Random Forest:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         5
         1.0       0.80      0.80      0.80         5
         2.0       0.96      0.96      0.96        23

    accuracy                           0.94        33
   macro avg       0.92      0.92      0.92        33
weighted avg       0.94      0.94      0.94        33

## 7) Training with cross validation

In [ ]:

models = { "Logistic Regression": LogisticRegression(max_iter=1000), "Decision Tree": DecisionTreeClassifier(), "Random Forest": RandomForestClassifier() } 
results = {} 
# Train and evaluate 
for name, model in models.items(): 
    scores = cross_val_score(model, X_train, y_train, cv=5, scoring="accuracy", n_jobs=-1) 
    results[name] = scores.mean()

In [206]:
print(results.values())

dict_values([np.float64(0.9772079772079773), np.float64(0.9695156695156696), np.float64(0.9772079772079773)])

In [210]:
print(f"Best Model: {max(results, key=results.get)} with Accuracy: {results[max(results, key=results.get)]:.4f}")

Best Model: Logistic Regression with Accuracy: 0.9772

The best model is the one with the highest average accuracy from cross-validation: **Logistic regression**